name: CICD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  security-check:
    runs-on: ubuntu-latest
    needs: compile
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Gitleaks
        run: sudo apt-get update && sudo apt-get install gitleaks -y

      - name: Run Gitleaks
        run: gitleaks detect --source . --report-path gitleaks-report.json --report-format json

  publish-gpr:
    needs: 
      - compile
      - security-check
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm ci

      - name: Bump version  # ✅ prevents 409 Conflict error
        run: npm version patch --no-git-tag-version

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

